version: '3.8'
services:
  db:
    image: postgres
    restart: always
    expose: 
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - "./db/data:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/eng-soft-clean-node-api
    restart: always
    command: bash -c "yarn && yarn migrations:run && yarn local" 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sbdd?schema=public
    volumes:
      - ./src/:/usr/src/eng-soft-clean-node-api/src/ 
      - ./tsconfig.json:/usr/src/eng-soft-clean-node-api/tsconfig.json 
      - ./tsconfig.build.json:/usr/src/eng-soft-clean-node-api/tsconfig.build.json 
      - ./package.json:/usr/src/eng-soft-clean-node-api/package.json
      - ./prisma:/usr/src/eng-soft-clean-node-api/prisma/
    ports: 
      - "3333:3333"
      - "9222:9222"
    links:
      - db