version: "3.8"
services:
  db:
    image: "bitnami/postgresql"
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=sbdd
    ports:
      - "5432:5432"
    networks:
      - app-net
  api:
    container_name: api-container-test
    build:
      context: ../
      dockerfile: .ci/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sbdd?schema=public
    ports:
      - "3333:3333"
      - "9222:9222"
    depends_on:
      - db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
