name: Homolog workflow

on:
  pull_request:
    branches:
      - homolog
      - main
    types: [synchronize, opened, reopened, ready_for_review, labeled]
  push:
    branches:
      - homolog

env:
  DATABASE_URL: ${{ secrets.HOMOLOG_DATABASE_URL }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Yarn Install
        run: yarn

      - name: Run migrations
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.HOMOLOG_DATABASE_URL }}

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_HOMOLOG_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
        env:
          DATABASE_URL: ${{ secrets.HOMOLOG_DATABASE_URL }}
